In [37]:
import numpy as np
import pandas as pd

In [38]:
dataset = pd.read_csv("./dataset/updated_accidents_data.csv")

In [39]:
x = dataset.iloc[:, 2:].values
y = dataset.iloc[:, 1].values

In [40]:
print(x)
print(y)
print(len(x), len(y))

[['Amavasya' 'Jyesta' 'Chatushpada' 'Ganda' '24 10\'32"' 'Vrushchika']
 ['Chaturdasi' 'Anuradha' 'Vishti' 'Soola' '24 10\'32"' 'Vrushchika']
 ['Sapthami' 'Makha' 'Vishti' 'Vishkambha' '24 10\'30"' 'Simha']
 ...
 ['Trayodasi' 'Satabhisham' 'Garaja' 'Subha' '24 9\'52"' 'Kumbha']
 ['Dasami' 'Chitta' 'Garaja' 'Variyan' '24 5\'11"' 'Kanya']
 ['Ashtami' 'Jyesta' 'Balava' 'Siddhi' '24 10\'45"' 'Vrushchika']]
[10067  9552  9256 ...     1     1     1]
2572 2572


In [41]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse=False)
x = encoder.fit_transform(x)
print(x)

print("\nCategories:")
print(encoder.categories_)


[[1. 0. 0. ... 0. 0. 1.]
 [0. 0. 1. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 1.]]

Categories:
[array(['Amavasya', 'Ashtami', 'Chaturdasi', 'Chavithi', 'Chaviti',
       'Dasami', 'Dvadasi', 'Ekadasi', 'Navami', 'Padyami', 'Panchami',
       'Punnami', 'Sapthami', 'Shasti', 'Thadiya', 'Trayodasi', 'Vidhiya'],
      dtype=object), array(['Aarudra', 'Anuradha', 'Ashwini', 'Aslesha', 'Bharani', 'Chitta',
       'Dhanista', 'Hasta', 'Jyesta', 'Kruthika', 'Makha', 'Mrugasira',
       'Mula', 'Pubha', 'Punarwasu', 'Purva-Bhadra', 'Purva-Shada',
       'Pushyami', 'Revathi', 'Rohini', 'Satabhisham', 'Sravanam',
       'Swati', 'Uttara', 'Uttara-Bhadra', 'Uttara-Shaada', 'Visakha'],
      dtype=object), array(['Balava', 'Bawa', 'Chatushpada', 'Garaja', 'Kaulava',
       'Kimstughana', 'Nagava', 'Sakuna', 'Taitula', 'Vanija', 'Vishti'],
      dtype=object), array(['Atiganda', 'Ayushman', 'Bramha', 'Dhrithi', 'Dhruva', 'Ga

C:\Users\siddh\AppData\Roaming\Python\Python310\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [42]:
print(x)

[[1. 0. 0. ... 0. 0. 1.]
 [0. 0. 1. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 1.]]


In [43]:
print(len(x))
print(len(y))

2572
2572


In [44]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 42)

In [45]:
print(x_train)
print(y_train)
print(x_test)
print(y_test)

[[0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]]
[  35 2511 1949 ... 3119 2914 3455]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 1. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]]
[3121  933  667 5139 1963 2215  964 2444 2765 1352 3902 3024 1094 5208
 4009 1676  684 2486 6292  791  613  615 7410 1779 2258  553 4055 3799
 7197 5868  599 2857 7567 2445  572  973  734  804 3047 3416 4367 1422
 3420 3141 6268 1489 1691 3090 1017 2852 3761 4408 2679 3254 3561 7230
 2926    3 3614 1582 3363 2872 3988  974 3136 4940 4856 1512 3044 6113
  937 1603 2620 3608 1114  633  750 2985 2423 1126 3016  560 3693 3967
  602 3456 3309 3565 7578 3355 3032 3757 3123 3239 5387 3928 5530 2827
   60 2407 1500 3666 2312 3120 4153 2524 3623 3684 2788 4205 2783 4057
 1290 4043  695  992  696 3058 3276 3951 1015 2111 2724 1454 4082 2918
 6179 4659 34

In [46]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor()
regressor.fit(x_train, y_train)

y_pred = np.array(regressor.predict(x_test))

In [47]:
for i in range(len(y_pred)):
    y_pred[i] = int(y_pred[i])

print(y_pred)

[2884. 2189. 1698. 4091. 2053. 3010. 1406. 4035. 2289. 2920. 5244. 2972.
 2207. 3844. 3241. 2520. 2506. 3349. 6254.  808.  391. 2020. 5459. 2543.
 2209. 2718. 5398. 2254. 6857. 7262. 2495. 3689. 6532. 2362. 1878. 2345.
 2670. 2382. 2592. 2339. 4879. 5768. 2843. 2661. 5752. 3478. 2336. 2643.
 2546. 2462. 2000. 2192. 2045. 2472. 2369. 5764. 1881. 1542. 1974. 1673.
 2704. 1754. 2678. 2343. 2144. 3572. 3737. 1952. 2199. 5328. 2368. 1579.
 2222. 2575. 2808. 1983. 1331. 1856. 3834. 2726. 2845. 1856. 5795. 3745.
 2625. 2544. 2442. 4081. 1562. 7352. 2458. 3120. 2341. 2425. 6513. 2946.
 6211. 2033.  488. 2505. 1788. 2982. 2589. 6263. 3021. 3373. 2830. 2506.
 2114. 2930. 2663. 2959. 2316. 4665. 2896. 2435. 2471. 2694. 2269. 5451.
 2866. 2584. 2298. 2391. 2569. 2338. 5282. 3822. 2247. 2754. 2647. 2013.
 5611. 4697. 2391. 5063. 6628. 6480. 2070. 2795. 5149. 3633. 4826. 3628.
 2782. 1999. 4591. 5847. 2292. 5617. 2111. 2428. 3860. 2975. 5463. 2256.
 3780. 2473. 2573. 5313. 2929. 6272. 1887. 2758. 10

In [48]:
from sklearn.metrics import r2_score

print(r2_score(y_true=y_test, y_pred = y_pred))

0.4225813142115409
